import { roadRect, sidewalkRects, type CampusLayout } from '../data/layout';

const ASPHALT = '#3a3f45';
const SIDEWALK = '#c9ccd1';
const DASH = '#e8e8e8';

/** Road with sidewalks and a dashed center line, generated by loop (no manual dozens). */
export default function Road({ campus }: { campus: CampusLayout }) {
  const road = roadRect(campus);
  const dashes = Math.floor(road.width / 4);
  return (
    <group>
      {/* asphalt */}
      <mesh rotation-x={-Math.PI / 2} position={[road.x, 0.02, road.z]} receiveShadow>
        <planeGeometry args={[road.width, road.depth]} />
        <meshStandardMaterial color={ASPHALT} />
      </mesh>
      {/* sidewalks */}
      {sidewalkRects(campus).map((s, i) => (
        <mesh key={i} rotation-x={-Math.PI / 2} position={[s.x, 0.02, s.z]} receiveShadow>
          <planeGeometry args={[s.width, s.depth]} />
          <meshStandardMaterial color={SIDEWALK} />
        </mesh>
      ))}
      {/* center dashes along X */}
      {Array.from({ length: dashes }, (_, i) => (
        <mesh
          key={i}
          rotation-x={-Math.PI / 2}
          position={[-road.width / 2 + 2 + i * 4, 0.03, road.z]}
        >
          <planeGeometry args={[2, 0.3]} />
          <meshStandardMaterial color={DASH} />
        </mesh>
      ))}
    </group>
  );
}
